name: Testes


on: [push, pull_request]


env:
  HOST: 127.0.0.1
  MYSQL_DATABASE: bd
  MYSQL_ROOT_PASSWORD: 123

jobs:

  testar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: docker
        working-directory: src/services/bd
        run: docker compose up -d --build --wait
        
      - name: interacao-bd-docker
        working-directory: src/services/bd
        run: dotnet run teste

      - name: testes-simples
        working-directory: src
        run: dotnet test --configuration Release -m